# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Conner Dailey
tagline:             'Physics graduate student, hobby photographer'
description:         'I am a former graduate student at the University of Nevada, Reno. I enjoy all types of photography, especially astrophotography.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
paginate_path:       '/Blog/page:num/'

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
